name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs: 
  build_arm:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - { system: 24.04 }
          - { system: devel }

    steps:
    - uses: actions/setup-python@main
      with:
          python-version: 3.12

    - name: 'Update system to devel'
      if: ${{ matrix.system == 'devel' }}
      run: |
        sudo sed -i 's/noble/devel/g' /etc/apt/sources.list.d/ubuntu.sources
        sudo apt update
        sudo apt-mark hold cloud-init-base

    - name: 'Install software packages'
      run: |
        sudo apt update
        sudo apt full-upgrade
        sudo apt install mono-complete gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu

    - uses: actions/checkout@main
      with: 
          submodules: 'true'

    - name: 'Build'
      env:
        GCC5_ARM_PREFIX: '/usr/bin/arm-linux-gnueabihf-'
        GCC5_AARCH64_PREFIX: '/usr/bin/aarch64-linux-gnu-'
      run: |
        pip install --upgrade -r pip-requirements.txt
        python MultiFlavorBuild.py --setup -a ARM,AARCH64 TOOL_CHAIN_TAG=GCC5
        python MultiFlavorBuild.py --update -a ARM,AARCH64 TOOL_CHAIN_TAG=GCC5
        python MultiFlavorBuild.py -a ARM,AARCH64 TOOL_CHAIN_TAG=GCC5

    - name: 'Upload artifact'
      if: ${{ always() }}
      uses: actions/upload-artifact@main
      with:
        name: ${{ format('ARM,AARCH64 (Ubuntu {0} Build)', matrix.system) }}
        path:  ${{ github.workspace }}/Build
        compression-level: 9

  build_x86:
    runs-on: windows-2025
    strategy:
      fail-fast: false

    steps:
    - uses: actions/setup-python@main
      with:
          python-version: 3.12

    - uses: actions/checkout@main
      with: 
          submodules: 'true'

    - name: 'Build'
      run: |
        pip install --upgrade -r pip-requirements.txt
        python MultiFlavorBuild.py --setup -a IA32,X64
        python MultiFlavorBuild.py --update -a IA32,X64
        python MultiFlavorBuild.py -a IA32,X64

    - name: 'Upload artifact'
      uses: actions/upload-artifact@main
      with:
        name: 'IA32_X64'
        path:  ${{ github.workspace }}\Build
        compression-level: 9

  bundle:
    needs: [build_arm, build_x86]
    runs-on: windows-2025
    strategy:
      fail-fast: false

    steps:
    - uses: actions/setup-python@main
      with:
          python-version: 3.12

    - uses: actions/checkout@main
      with: 
          submodules: 'true'

    - name: 'Download artifacts'
      uses: actions/download-artifact@main

    - name: 'Build'
      run: |
        ls
        ls Build
        pip install --upgrade -r pip-requirements.txt
        python MultiFlavorBuild.py --setup
        python MultiFlavorBuild.py --update
        python MultiFlavorBuild.py --bundle

    - name: 'Upload artifact'
      uses: actions/upload-artifact@main
      with:
        name: 'Bundle'
        path:  ${{ github.workspace }}\Bundle
        compression-level: 9